const connectDB = require("./db_connection");
const express = require("express");
const cors = require("cors");
const helmet = require("helmet");
const Teacher = require("./models/Teacher");
// const bcrypt = require("bcryptjs");
connectDB();
const app = express();
app.use(cors());
app.use(helmet());
app.use(express.json());
app.get("/", async (req, res) => {
  const t = await Teacher.findById("6361501360cfaf021937d914");
  res.send(t);
});
app.use("/api/auth", require("./routes/auth"));
app.use("/api/purchase", require("./routes/purchases"));
app.use("/api/materials", require("./routes/materials"));
app.use("/api/withdrawal", require("./routes/withdrawals"));
app.listen(8000, () => console.log("Server running..."));
